[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | build
  | dist
  | deps
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["proxy_project"]
skip = ["venv", "deps", ".git"]